"""
Django settings for suorganizer project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
from .log_filters import ManagementFilter
import os
from django.conf.global_settings import EMAIL_BACKEND, DEFAULT_FROM_EMAIL,\
    EMAIL_SUBJECT_PREFIX, SERVER_EMAIL, MANAGERS, STATICFILES_DIRS, LOGIN_URL,\
    LOGOUT_REDIRECT_URL, FIXTURE_DIRS, INTERNAL_IPS
import suorganizer
from django.urls import reverse_lazy
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '34*gu3sv2s9e0zv_5)z(iu5(e77scbvsvp-bpol-wpso@w-(wa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# User
# https://docs.djangoproject.com/en/1.8/topics/auth/customizing/
AUTH_USER_MODEL = 'user.User'
ALLOWED_HOSTS = []
SITE_ID = 1
LOGIN_URL = reverse_lazy('userr:user_login')
LOGOUT_URL = reverse_lazy('userr:user_logout')
LOGIN_REDIRECT_URL = 'organizer:organizer_tag_list'
#LOGOUT_REDIRECT_URL = 'user:login'
#LOGOUT_REDIRECT_URL = 'user:login'
CRISPY_TEMPLATE_PACK = "bootstrap4"
# Application definition
CHROMEDRIVER = os.path.join(BASE_DIR, '../chromedriver')

EMAIL_BACKEND  = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
#EMAIL_HOST_USER = 'mostafa-pc'
EMAIL_HOST_USER = 'mostafaitalian1379@gmail.com'
DEFAULT_FROM_EMAIL = 'mostafaitalian1379@gmail.com'
EMAIL_SUBJECT_PREFIX = '[suorganizer]'
SERVER_EMAIL = 'mostafaitalian1379@gmail.com'
#MANAGERS = (('us', 'italiano_heiahoooo@hotmail.com'),)

#EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')
EMAIL_HOST_PASSWORD = '100aa100'
EMAIL_USE_TLS = True
# Application definition

INSTALLED_APPS = [
    'organizer',
    'blog',
    'user',
    'markdownify',
    'contact',
    'crispy_forms',
    'debug_toolbar',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
    'django.contrib.sites',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'suorganizer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'suorganizer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
verbose = ("[%(asctime)s] %(levelname)s ",
           "[%(name)s:%(lineno)s] %(message)s")
LOGGING = {'version': 1,
           'disable_existing_loggers': False,
           'filters' : {'remove_migration_sql' : {'()' : ManagementFilter}},
           'handlers': {'console':{'filters': ['remove_migration_sql'],'class':'logging.StreamHandler',}},
           'formatters': {'verbose': {'format': verbose,
                                      'datefmt': "%Y-%b-%d %H:%M:%S"},},
           'loggers': {'django': {
               'handlers': ['console'],
               'level': 'DEBUG',
               'formatter': 'verbose'},},}
#disablle_existing_loggers   to disable any other loggers
# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Africa/Cairo'


USE_I18N = True

USE_L10N = True

USE_TZ = True

INTERNAL_IPS='127.0.0.1'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),]
FIXTURE_DIRS=[os.path.join(BASE_DIR,'fixtures')]