# Generated by Django 2.1.4 on 2019-02-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190216_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date', 'title'], 'permissions': (('view_future_post', 'can view unpublished posts'),), 'verbose_name': 'blog post'},
        ),
    ]
